modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Polymeta/WonderTrade/issues"
license = "MIT License"

[[mods]]
modId = "wondertrade"
version = "${version}"
displayName = "WonderTrade"
authors = "Polymeta"
description = '''
A wondertrade sidemod written for cobblemon
'''
#logoFile = ""

[[dependencies.wondertrade]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.69,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.3.1,)"
ordering = "AFTER"
side = "BOTH"