modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Polymeta/WonderTrade/issues"
license = "MIT License"

[[mods]]
modId = "wondertrade"
version = "${version}"
displayName = "WonderTrade"
authors = "Polymeta"
description = '''
A wondertrade sidemod written for cobblemon
'''
#logoFile = ""

[[dependencies.wondertrade]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "AFTER"
side = "BOTH"