modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Polymeta/WonderTrade/issues"
license = "MIT License"

[[mods]]
modId = "wondertrade"
version = "${version}"
displayName = "WonderTrade"
authors = "Polymeta"
description = '''
A wondertrade sidemod written for cobblemon
'''
#logoFile = ""

[[dependencies.wondertrade]]
modId = "neoforge"
mandatory = true
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wondertrade]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"